-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 05:15:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elimubora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elimubora` ;

-- -----------------------------------------------------
-- Schema elimubora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elimubora` DEFAULT CHARACTER SET utf8 ;
USE `elimubora` ;

-- -----------------------------------------------------
-- Table `elimubora`.`taasisi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`taasisi` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`taasisi` (
  `idtaasisi` INT NOT NULL AUTO_INCREMENT,
  `taasisi_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtaasisi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elimubora`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`users` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `taasisiid` INT NULL,
  `full_name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`),
  INDEX `taasisiid_idx` (`taasisiid` ASC) VISIBLE,
  CONSTRAINT `taasisiid`
    FOREIGN KEY (`taasisiid`)
    REFERENCES `elimubora`.`taasisi` (`idtaasisi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elimubora`.`reset_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`reset_code` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`reset_code` (
  `idreset_code` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `code` VARCHAR(45) NULL,
  `time` TIME NULL,
  PRIMARY KEY (`idreset_code`),
  INDEX `userid_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `elimubora`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elimubora`.`batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`batch` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`batch` (
  `idbatch` INT NOT NULL AUTO_INCREMENT,
  `taasisi_id` INT NULL,
  `year` INT NULL,
  `starts` DATE NULL,
  `ends` DATE NULL,
  `fee` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idbatch`),
  INDEX `taasisi_id_idx` (`taasisi_id` ASC) VISIBLE,
  CONSTRAINT `taasisi_id`
    FOREIGN KEY (`taasisi_id`)
    REFERENCES `elimubora`.`taasisi` (`idtaasisi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elimubora`.`wanafunzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`wanafunzi` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`wanafunzi` (
  `idwanafunzi` INT NOT NULL AUTO_INCREMENT,
  `batch_id` INT NULL,
  `regdate` DATE NULL,
  `student_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `parent_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idwanafunzi`),
  INDEX `batch_id_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `batch_id`
    FOREIGN KEY (`batch_id`)
    REFERENCES `elimubora`.`batch` (`idbatch`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elimubora`.`fee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elimubora`.`fee` ;

CREATE TABLE IF NOT EXISTS `elimubora`.`fee` (
  `idfee` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NULL,
  `pay_date` INT NULL,
  `amount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idfee`),
  INDEX `student_id_idx` (`student_id` ASC),
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `elimubora`.`wanafunzi` (`idwanafunzi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
